apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating for mvnwebapp
metadata:
  name: mvnwebapp
spec:
  selector:
    matchLabels:
      app: mvnwebapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mvnwebapp
    spec:
      containers:
        - name: mvnwebapp
          image: mahfuzlove/mvn0.1 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090 # The port that the container is running on in the cluster
