apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating for mvnwebapp
metadata:
  name: mvnwebapp
spec:
  selector:
    matchLabels:
      app: mvnwebapp
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mvnwebapp
    spec:
      containers:
        - name: mvnwebapp
          image: mahfuzlove/mvn0.1 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: mvnwebapp-demo-service
spec:
  selector:
    app: mvnwebapp
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: ClusterIP # type of the service.
